/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package websitedetectionui;

/**
 *
 * @author Subu
 */
public class TabPanel extends javax.swing.JPanel {

    /**
     * Creates new form TabPanel2
     */
    public TabPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        addNewWPageTab1 = new websitedetectionui.AddNewWPageTab();
        managePatternsTab1 = new websitedetectionui.ManagePatternsTab();
        vocabMinerTab1 = new websitedetectionui.VocabMinerTab();

        jTabbedPane1.addTab("Web Page Viewer", addNewWPageTab1);
        jTabbedPane1.addTab("Manage Patterns", managePatternsTab1);
        jTabbedPane1.addTab("Vocab Miner", vocabMinerTab1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private websitedetectionui.AddNewWPageTab addNewWPageTab1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private websitedetectionui.ManagePatternsTab managePatternsTab1;
    private websitedetectionui.VocabMinerTab vocabMinerTab1;
    // End of variables declaration//GEN-END:variables
}
